// Catálogo padrão — usado como reserva se o Firebase não estiver configurado
// e como semente inicial do Firestore na primeira vez que o painel abre.
// A partir daí, tudo é lido/salvo no Firestore e editado pelo admin.html.
const FALLBACK_PRODUCTS = [
  {
    id: "p1",
    name: "Whisky Red Label 1L",
    category: "Bebidas",
    price: 119.9,
    originalPrice: 139.9,
    image: "assets/products/whisky.jpg",
    description: "Whisky escocês blended, garrafa 1 litro.",
    available: true,
  },
  {
    id: "p2",
    name: "Vodka Smirnoff 998ml",
    category: "Bebidas",
    price: 59.9,
    image: "assets/products/vodka.jpg",
    description: "Vodka tripla destilação, garrafa 998ml.",
    available: true,
  },
  {
    id: "p3",
    name: "Cerveja Heineken Long Neck (Pack c/6)",
    category: "Bebidas",
    price: 39.9,
    originalPrice: 47.9,
    image: "assets/products/cerveja.jpg",
    description: "Pack com 6 long necks 330ml geladas.",
    available: true,
  },
  {
    id: "p4",
    name: "Energético Red Bull 250ml",
    category: "Bebidas",
    price: 9.9,
    image: "assets/products/redbull.jpg",
    description: "Lata individual gelada.",
    available: true,
  },
  {
    id: "p5",
    name: "Narguilé Completo Premium",
    category: "Narguilés",
    price: 249.9,
    originalPrice: 299.9,
    image: "assets/products/narguile_completo.jpg",
    description: "Narguilé completo com vaso de vidro, mangueira lavável e acessórios.",
    available: true,
  },
  {
    id: "p6",
    name: "Narguilé Compacto Portátil",
    category: "Narguilés",
    price: 149.9,
    image: "assets/products/narguile_compacto.jpg",
    description: "Modelo compacto, ideal pra levar pra qualquer lugar.",
    available: false,
  },
  {
    id: "p7",
    name: "Essência Adalya 50g — Two Apples",
    category: "Essências",
    price: 34.9,
    image: "",
    description: "Essência premium sabor maçã dupla, lata 50g.",
    available: true,
  },
  {
    id: "p8",
    name: "Essência Al Fakher 50g — Menta",
    category: "Essências",
    price: 29.9,
    originalPrice: 34.9,
    image: "",
    description: "Essência tradicional sabor menta, lata 50g.",
    available: true,
  },
  {
    id: "p9",
    name: "Carvão Coco Premium (1kg)",
    category: "Acessórios",
    price: 29.9,
    image: "assets/products/carvao.jpg",
    description: "Carvão de coco natural, queima longa e sem cheiro forte.",
    available: true,
  },
  {
    id: "p10",
    name: "Piteira Descartável (Pacote c/50)",
    category: "Acessórios",
    price: 19.9,
    image: "",
    description: "Piteiras individuais descartáveis, pacote com 50 unidades.",
    available: true,
  },
  {
    id: "p11",
    name: "Gin Tanqueray 750ml",
    category: "Bebidas",
    price: 129.9,
    originalPrice: 149.9,
    image: "assets/products/gin.png",
    description: "Gin premium London Dry, garrafa 750ml.",
    available: true,
  },
  {
    id: "p12",
    name: "Cooler Térmico para Bebidas",
    category: "Acessórios",
    price: 44.9,
    image: "",
    description: "Cooler térmico compacto, mantém a bebida gelada por horas.",
    available: true,
  },
];
